### ISSUE TITLE
Would you consider allowing the Re-RxJS team to use this package name?

### ISSUE THREAD

**Issue by josepot** [jarlah/react-rxjs#19]
Hi @jarlah !

My name is Josep and I'm the creator of [Re-RxJS](https://github.com/re-rxjs/re-rxjs#re-rxjs). Re-RxJS is the result of lots of hours invested into trying to come up with a set of react-rxjs bindings that take full advantage of React latest features (hooks, Suspense and Concurrent Mode). However, we haven't published our first stable release yet.

Re-RxJS takes a different approach than React-RxJS does, because by default our bindings do not put flux-like stores at the forefront. It's still possible to use them, of course, but we don't wan't to have them as first-class citizens of these bindings. Another important difference is the fact that we are able to fully leverage React-Suspense and React Concurrent Mode features like `useTransition`.

Also, as of today, Re-RxJS is the only set of bindings that -while using state that lives outside of React- are [able to work without causing tearing issues on CM](https://github.com/dai-shi/will-this-react-global-state-work-in-concurrent-mode#results).

We have not announced the library yet, but we are planning to do that soon, as soon as we publish our first stable release :slightly_smiling_face:.

The thing is that we are not very happy with the name `re-rxjs` :grimacing: and the name that we really wished we had is `react-rxjs`. Looking at the npm-stats, I've noticed the low number in the "weekly download" section and I have also noticed that the latest release was 8 months ago. So, I was wondering if you would be so kind to let us publish our first stable version on the `react-rxjs` package :pray:. We would do that using version `3.0.0`, and of course: we wouldn't unpublish any of the versions that have been published so far. Also, if version 2 needed further patches or minor updates we would be more than happy to let you handle those, of course. And lastly -regardless of what your answer is to this inquiry- I would love to get feedback from you on Re-RxJS and to have you as a contributor.

Thanks,

Josep

**Comment by jarlah** [comment]
for me, I really don't care. I would never ever use my own project for anything. You know when you have worked for ages, and you look back and wish you didn't look back? This project is something I would see if I looked back. I regret implementing it, and publishing it. 

But help me out here, what could I call it instead? react-flux-rxjs? Something like that ? I have no idea how I would rename my npm package, and I would really not waste any of my energy on finding out how I could. I would even resist to run some commands for it. The simplest for me would just be to delete the thing from npmjs.

**Comment by jarlah** [comment]
I saw in mail that they can transfer ownership of react-rxjs in npm for me. So yey I don't have to lift a finger.

**Comment by josepot** [comment]
> for me, I really don't care. I would never ever use my own project for anything. You know when you have worked for ages, and you look back and wish you didn't look back? This project is something I would see if I looked back. I regret implementing it, and publishing it.
> 
> But help me out here, what could I call it instead? react-flux-rxjs? Something like that ? I have no idea how I would rename my npm package, and I would really not waste any of my energy on finding out how I could. I would even resist to run some commands for it. The simplest for me would just be to delete the thing from npmjs.

Hi Jarl,

First of: Thanks a lot for getting back to me so quickly and for being so cooperative. For real, thank you so much!

Also, I'm very-sorry if my comment came across as me being judgmental. I don't think that you did anything wrong. Also, it wouldn't be fair to judge a project that got started 3 years ago with today's eyes.

Thanks,

Josep

**Comment by jarlah** [comment]
@josepot changed my GitHub repos name. take it now, fast before anyone else does :D
